sudo: required
language: csharp
mono: none
dotnet: 2.0.0
dist: trusty

# services:
#  - docker

script:
 - dotnet restore
 - dotnet build
 - dotnet pack -c Release --include-symbols
 - dotnet test src/Test/AspNetCore.Proxy.Tests.csproj
