name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout!
      uses: actions/checkout@v1
    - name: Setup .NET Environment.
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.401'
    - name: Build and run tests.
      run: dotnet test --collect:"XPlat Code Coverage"
    - name: Make artifacts directory.
      run: mkdir -p artifacts
    - name: Copy artifacts.
      run: |
        find . -type f -name AspNetCore.Proxy.*.nupkg -exec cp '{}' ./artifacts/package.nupkg ';'
        find . -type f -name coverage.*.xml -exec cp '{}' ./artifacts/coverage.xml ';'
    - name: Upload artifacts.
      uses: actions/upload-artifact@master
      with:
        name: artifacts
        path: artifacts
    
