name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout!
      uses: actions/checkout@v1
    - name: Setup .NET Environment.
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.401'
    - name: Build and run tests.
      run: dotnet test --collect:"XPlat Code Coverage"
    - name: Upload coverage.
      uses: actions/upload-artifact@master
      with:
        name: coverage.xml
        path: '**/coverage.*.xml'
    - name: Upload package.
      uses: actions/upload-artifact@master
      with:
        name: package.nupkg
        path: '**/AspNetCore.Proxy.*.nupkg'
    
