name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout!
      uses: actions/checkout@v1
    - name: Setup .NET Environment.
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.401'
    - name: Build and run tests.
      run: |
        dotnet test
